services:
  web:
    build: .
    envVars:
      - key: PORT
        value: 80
      - key: DB_HOST
        fromDatabase:
          name: mysql
          property: host
      - key: DB_USER
        fromDatabase:
          name: mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysql
          property: password
      - key: DB_NAME
        value: attendance_monitoring
    routes:
      - path: /
        matchType: PATH_PREFIX
    startCommand: apache2-foreground

databases:
  - name: mysql
    engine: mysql
    version: "8.0"
    plan: free
